# Generated by Django 2.0.3 on 2018-03-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('team', models.CharField(max_length=20)),
                ('strenght', models.PositiveIntegerField()),
                ('instinct', models.PositiveIntegerField()),
                ('covert', models.PositiveIntegerField()),
                ('tech', models.PositiveIntegerField()),
                ('energy', models.PositiveIntegerField()),
            ],
        ),
    ]
