# Generated by Django 2.0.3 on 2018-06-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_player', models.BooleanField(default=False)),
                ('win', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Henchman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('strenght', models.PositiveIntegerField()),
                ('instinct', models.PositiveIntegerField()),
                ('covert', models.PositiveIntegerField()),
                ('tech', models.PositiveIntegerField()),
                ('energy', models.PositiveIntegerField()),
                ('piercing_energy', models.BooleanField(default=False)),
                ('teleport', models.BooleanField(default=False)),
                ('x_gene', models.BooleanField(default=False)),
                ('versatile', models.BooleanField(default=False)),
                ('soaring_flight', models.BooleanField(default=False)),
                ('lightshow', models.BooleanField(default=False)),
                ('berserk', models.BooleanField(default=False)),
                ('split_cards', models.BooleanField(default=False)),
                ('recruitment_points', models.PositiveIntegerField(choices=[(0, 'None'), (1, 'A few'), (2, 'Medium'), (3, 'A lot of')], default=0)),
                ('costs', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mastermind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legendary.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='henchman_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='henchman_1', to='legendary.Henchman'),
        ),
        migrations.AddField(
            model_name='game',
            name='henchman_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='henchman_2', to='legendary.Henchman'),
        ),
        migrations.AddField(
            model_name='game',
            name='hero_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hero_1', to='legendary.Hero'),
        ),
        migrations.AddField(
            model_name='game',
            name='hero_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hero_2', to='legendary.Hero'),
        ),
        migrations.AddField(
            model_name='game',
            name='hero_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hero_3', to='legendary.Hero'),
        ),
        migrations.AddField(
            model_name='game',
            name='hero_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero_4', to='legendary.Hero'),
        ),
        migrations.AddField(
            model_name='game',
            name='hero_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero_5', to='legendary.Hero'),
        ),
        migrations.AddField(
            model_name='game',
            name='mastermind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legendary.Mastermind'),
        ),
        migrations.AddField(
            model_name='game',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legendary.Scheme'),
        ),
        migrations.AddField(
            model_name='game',
            name='villains_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villains_1', to='legendary.Villain'),
        ),
        migrations.AddField(
            model_name='game',
            name='villains_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='villains_2', to='legendary.Villain'),
        ),
        migrations.AddField(
            model_name='game',
            name='villains_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='villains_3', to='legendary.Villain'),
        ),
        migrations.AddField(
            model_name='game',
            name='villains_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='villains_4', to='legendary.Villain'),
        ),
    ]
