# Generated by Django 2.0.3 on 2018-03-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legendary.Team'),
        ),
    ]
