# Generated by Django 2.0.3 on 2018-03-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0003_auto_20180318_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hero',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legendary.Team'),
        ),
    ]
