# Generated by Django 2.0.3 on 2018-03-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0004_auto_20180318_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='piercing_energy',
            field=models.BooleanField(default=False),
        ),
    ]
