# Generated by Django 2.0.3 on 2018-03-18 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0006_hero_teleport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='strenght',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(14)]),
        ),
    ]
