# Generated by Django 2.0.3 on 2018-03-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0007_auto_20180318_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='recruitment_points',
            field=models.PositiveIntegerField(choices=[('None', 0), ('A few', 1), ('Medium', 2), ('A lot of', 3)], default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='instinct',
            field=models.CharField(choices=[(1, '1'), (2, '2')], max_length=200),
        ),
    ]
