# Generated by Django 2.0.3 on 2018-03-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0009_remove_hero_recruitment_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='instinct',
            field=models.CharField(max_length=200),
        ),
    ]
