# Generated by Django 2.0.3 on 2018-03-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0010_auto_20180319_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='covert',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hero',
            name='energy',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strenght',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='tech',
            field=models.CharField(max_length=20),
        ),
    ]
