# Generated by Django 2.0.3 on 2018-03-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0012_auto_20180319_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='recruitment_points',
            field=models.PositiveIntegerField(choices=[(0, 'None'), (1, 'A few'), (2, 'Medium'), (3, 'A lot of')], default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='covert',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='energy',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='instinct',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strenght',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='tech',
            field=models.PositiveIntegerField(),
        ),
    ]
