# Generated by Django 2.0.3 on 2018-03-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legendary', '0014_hero_x_gene'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='versatile',
            field=models.BooleanField(default=False),
        ),
    ]
